# Generated by Django 3.2 on 2022-11-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_comment'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
