# Generated by Django 3.2 on 2022-12-04 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='created_on',
        ),
        migrations.AddField(
            model_name='subscribedusers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
    ]
