# Generated by Django 3.2 on 2022-12-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221204_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
