# Generated by Django 3.2 on 2022-11-19 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20221110_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.ManyToManyField(blank=True, related_name='product_rate', to=settings.AUTH_USER_MODEL),
        ),
    ]
