# Generated by Django 3.2 on 2022-12-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
